services:
  - type: web
    name: todo-api
    env: node
    rootDir: api
    buildCommand: "npm install"
    startCommand: "npm start"
    plan: free
    autoDeploy: true

  - type: web
    name: todo-frontend
    env: node
    rootDir: frontend
    buildCommand: "npm install && npm run build"
    startCommand: "npm run preview"
    staticPublishPath: dist
    plan: free
    autoDeploy: true

databases:
  - name: todo-db
    plan: free
